config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :users
  resources :roles
  resources :committees
  resources :constituencies

  resources :results do

    collection do

       get :sum

    end

  end

   authenticated :user do

    root :to => 'welcome#index_admin', as: :authenticated_root

  end

    root :to => 'welcome#index'   

end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
   validates :name, presence: true
   validates :number, presence: true
   validates :town, presence: true 
   validates :seats, presence: true
   validates :electors, presence: true
   validates_format_of :town, :with => /\A\p{Lu}{1}\p{L}{2,}(\-{1}\p{Lu}{1}\p{L}{2,})*\z/,
     :message => "jest niepoprawna!"
   validates_numericality_of :number, :greater_than => 0
   validates_numericality_of :seats, :greater_than => 0
   validates_numericality_of :electors, :greater_than => 0
   validates_uniqueness_of :number
   validates_uniqueness_of :name
 
   has_many :results, dependent: :destroy
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_constituency, only: [:show, :edit, :update, :destroy]

  # GET /constituencies
  # GET /constituencies.json
  def index
    @constituencies = Constituency.all
  end

  # GET /constituencies/1
  # GET /constituencies/1.json
  def show
  end

  # GET /constituencies/new
  def new
    @constituency = Constituency.new
  end

  # GET /constituencies/1/edit
  def edit
  end

  # POST /constituencies
  # POST /constituencies.json
  def create
    @constituency = Constituency.new(constituency_params)

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Dodano okręg.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1
  # PATCH/PUT /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to @constituency, notice: 'Zmieniono dane.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1
  # DELETE /constituencies/1.json
  def destroy
    @constituency.destroy
    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: 'Okręg został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_constituency
      @constituency = Constituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def constituency_params
      params.require(:constituency).permit(:number, :name, :town, :seats, :electors)
    end
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
end

app/views/constituencies/_form.html.erb
<%= form_for(@constituency) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>Wystąpiły Błędy:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field col-md-3 form-group">
    <label>Numer:</label>
    <%= f.number_field :number, class: "form-control input-md" %>
  </div>
  <div class="field col-md-10 form-group">
    <label>Nazwa:</label>
    <%= f.text_field :name, class: "form-control input-md" %>
  </div>
  <div class="field col-md-12 form-group">
    <label>Miejscowość:</label>
    <%= f.text_field :town, class: "form-control input-md" %>
  </div>
  <div class="field col-md-3 form-group">
    <label>Liczba mandatów:</label>
    <%= f.number_field :seats, class: "form-control input-md" %>
  </div>
  <div class="field col-md-3 form-group">
    <label>Liczba wyborców:</label>
      <%= f.number_field :electors, class: "form-control input-md" %>
    </div>
  <div class="sm-offset-0 col-sm-10">
    <%= f.submit "Potwierdź", class: "btn btn-info" %><br>
  </div>
<% end %>

app/views/constituencies/edit.html.erb
<div class="container">
  <div class="panel-heading"><h3 class="intro-text text-center">Edytuj Okręg</div>
    <div>
      <%= render 'form' %>
    </div>
</div>
    <div>
       <ul class="pager">
         <li><%= link_to 'Powrót', constituencies_path %></li>
       </ul>
     </div>

app/views/constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista okręgów wyborczych</h1>

<table class="table">
  <thead>
    <tr>
      <th>Numer</th>
      <th>Nazwa</th>
      <th>Miejscowość</th>
      <th>Ilość mandatów</th>
      <th>Liczba osób uprawnionych do głosowania</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.number %></td>
        <td><%= constituency.name %></td>
        <td><%= constituency.town %></td>
        <td><%= constituency.seats %></td>
        <td><%= constituency.electors %></td>
        <td><%= link_to 'Wyświetl', constituency %></td>
        <td><%= link_to 'Edytuj', edit_constituency_path(constituency) %></td>
        <td><%= link_to 'Usuń', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Constituency', new_constituency_path %>

app/views/constituencies/new.html.erb
<div class="container">
    <div class="panel-info">
      <h3 class="intro-text text-center">
        Dodaj nowy okręg wyborczy
      </h3>
    </div>
    <div>
      <%= render 'form' %>
    </div>
</div>
   <div>
    <ul class="pager">
      <li><%= link_to 'Powrót', constituencies_path %></li>
    </ul>
</div>

app/views/constituencies/show.html.erb
<div class="container">
  <div class="col-md-offset-5">
   <div class="panel-heading">
      <h3<%= @constituency.name %></h3>
    </div>
    <div class=".col-md-push-6">
      <p>
	<strong>Numer:</strong>
        <%= @constituency.number %>
      </p>
      <p>
	<strong>Miejscowość:</strong>
	<%= @constituency.town %>
      </p>
      <p>
        <strong>Ilość mandatów:</strong>
	<%= @constituency.seats %>
      </p>
      <p>
	<strong>Liczba osób uprawnionych do głosowania:</strong>
	<%= @constituency.electors %>
      </p>
    </div>
    <div>
      <p class="intro-text text-center">
	<%= link_to 'Edytuj', edit_constituency_path(@constituency), class: "btn btn-primary" %> 
      </p>
    </div>
  </div>
</div>
 <div>
  <ul class="pager">
    <li><%= link_to 'Powrót', constituencies_path %></li>
  </ul>
</div>