config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :users
  resources :roles
  resources :committees
  resources :constituencies

  resources :results do

    collection do

       get :sum

    end

  end

   authenticated :user do

    root :to => 'welcome#index_admin', as: :authenticated_root

  end

    root :to => 'welcome#index'   

end

app/models/result.rb
class Result < ActiveRecord::Base
   validates :committee, presence: true
   validates :constituency, presence: true
   validates :amount, presence: true
   validates_numericality_of :amount, :greater_than_or_equal_to => 0   
   validates :committee, :constituency,  uniqueness: {scope: [:committee, :constituency] }

   belongs_to :committee
   belongs_to :constituency

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
before_filter :authenticate_user!
load_and_authorize_resource
# GET /results
# GET /results.json
def index
end
# GET /results/1
# GET /results/1.json
def show
end
# GET /results/new
def new
@result = Result.new
end
# GET /results/1/edit
def edit
end
# POST /results
# POST /results.json
def create
respond_to do |format|
if @result.save
format.html { redirect_to @result, notice: 'Dodano wyniki.' }
format.json { render :show, status: :created, location: @result }
else
format.html { render :new }
format.json { render json: @result.errors, status: :unprocessable_entity }
end
end
end
# PATCH/PUT /results/1
# PATCH/PUT /results/1.json
def update
respond_to do |format|
if @result.update(result_params)
format.html { redirect_to @result, notice: 'Zmieniono wyniki.' }
format.json { render :show, status: :ok, location: @result }
else
format.html { render :edit }
format.json { render json: @result.errors, status: :unprocessable_entity }
end
end
end
# DELETE /results/1
# DELETE /results/1.json
def destroy
@result.destroy
respond_to do |format|
format.html { redirect_to results_url, notice: 'Wynik został usunięty.' }
format.json { head :no_content }
end
end

def sum
  @result = Result.select('committee_id, sum(amount) as wynik').group('committee_id')
  

end
   

  private

    def result_params
      params.require(:result).permit(:committee_id, :constituency_id, :amount)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>Wystąpiły Błędy:</h2>
      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-8 form-group">
    <%= f.label :committee_id, "Komitet" %><br>
    <%= collection_select(:result, :committee_id, Committee.all, :id, :name, {prompt:true}, class: "form-control input-md" ) %>
  </div>
  <div class="field col-md-8 form-group">
    <%= f.label :constituency_id," Okręg" %><br>
    <%= collection_select(:result, :constituency_id, Constituency.all, :id, :name, {prompt:true}, class: "form-control input-md" ) %>
  </div>
  <div class="field col-md-3 form-group">
    <%= f.label :amount, "Głosy" %><br>
    <%= f.number_field :amount, class: "form-control input-md" %>
  </div>
  <div class="sm-offset-0 col-sm-10">
    <%= f.submit "Potwierdź", class: "btn btn-info" %>
  </div>
<% end %>

app/views/results/committee_result.html.erb
<p id="notice"><%= notice %></p>

<h1>Wyniki Komitetów</h1>

<table>
  <thead>
    <tr>
      <th>Komitet</th>
      <th>Wynik</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.committee_id %></td>
        <td><%= Result.sum %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/edit.html.erb
<div class="container">
  <div class="panel-heading"><h3 class="intro-text text-center">Edytuj Wyniki</div>
    <div class="col-md-offset-1 panel-default">
      <div class="form-horizontal">
       <%= render 'form' %>
    </div> 
    </div>
</div>
<div>
  <ul class="pager">
    <li><%= link_to 'Powrót', results_path %></li>
  </ul>
</div>

app/views/results/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
  <div class="table-responsive">
    <div class="panel panel-default">
      <div class="panel-heading">Wyniki</div>
        <table class="table table-bordered table-condensed table-striped">
	  <thead>
	    <tr>
	      <th>Komitet</th>
	      <th>Okręg</th>
	      <th>Głosy</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>
	  <tbody>
	  <% @results.each do |result| %>
	      <tr>
		<td><%= result.committee.name %></td>
		<td><%= result.constituency.name %></td>
		<td><%= result.amount %></td>
		<td><%= link_to 'Wyświetl', result %></td>
		<td><%= link_to 'Edytuj', edit_result_path(result) %></td>
		<td><%= link_to 'Usuń', result, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
      </div>
    </div>
  <div class= "col-xs-offset-11">
    <%= link_to 'Dodaj', new_result_path, class: "btn btn-primary" %>
  </div>
  <div class="col-lg-offset-4">
    <%= link_to 'Wyniki komitetów', result_path('sum'), class: "btn btn-info col-xs-6" %>
  </div>
</div>
</div>

app/views/results/new.html.erb
<div class="container">
  <div class="content">
    <div class="panel-info">
      <h3 class="intro-text text-center">
        Dodaj wyniki
      </h3>
    </div>
    <div class="col-md-offset-1">
      <%= render 'form' %>
    </div>
  </div>
</div>
  <div>
    <ul class="pager">
      <li><%= link_to 'Powrót', results_path %></li>
    </ul>
  </div>

app/views/results/show.html.erb
<div class="container">
     <div class="panel-heading">
      <h3 class="intro-text text-center"><%= @result.committee.name %></h3>
    </div>
    <div class="intro-text text-center">
      <p>
       <h4><strong>Okręg nr</strong>
        <%= @result.constituency.number %></h4>
      </p>
      <p>
      <h4> <strong>Głosy otrzymane w okręgu:</strong>
       <%= @result.amount %></h4>
      </p>
    </div>
    <div>
      <p class="intro-text text-center">
        <%= link_to 'Edytuj', edit_result_path(@result), class: "btn btn-primary" %>
      </p>
    </div>
    <div>
      <ul class="pager">
        <li><%= link_to 'Powrót', results_path %></li>
      </ul>
    </div>
</div>

app/views/results/sum.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="table-responsive">
    <div class="panel panel-default">
      <div class="panel-heading">Wyniki</div>
        <table class="table table-bordered table-condensed table-striped">
	  <thead>
	    <tr>
	      <th>Komitet</th>
              <th>Głosy</th>
              <th colspan="3"></th>
            </tr>
           </thead>
           <tbody> 
           <% @result.each do |result| %>
             <tr>
               <td><%= result.committee.name %></td>
               <td><%= result.wynik %></td>
             </tr>
           <% end %>
         </tbody>
       </table>
     </div>
   </div>
 </div>
  <div>
      <ul class="pager">
	<li><%= link_to 'Powrót', results_path %></li>
      </ul>
    </div>
</div>