config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :users
  resources :roles
  resources :committees
  resources :constituencies

  resources :results do

    collection do

       get :sum

    end

  end

   authenticated :user do

    root :to => 'welcome#index_admin', as: :authenticated_root

  end

    root :to => 'welcome#index'   

end

app/models/committee.rb
class Committee < ActiveRecord::Base
   validates :name, presence: true
   validates_uniqueness_of :name 
   has_attached_file :logo, styles: { :medium => "300x300>", :thumb => "100x100>" } 
   validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
   
   has_many :results, dependent: :destroy
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

 # before_action :set_committee, only: [:show, :edit, :update, :destroy]

  # GET /committees
  # GET /committees.json
  def index
   # @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  end

  # GET /committees/new
  def new
   # @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
   # @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Dodano nowy Komitet.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Zmienino dane.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Komitet został usunięty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
   # def set_committee
     # @committee = Committee.find(params[:id])
   # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name, :logo)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for @committee, html: { multipart: true } do |f| %>
  <% if @committee.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @commitee.errors.full_messages.each do |msg| %>
          <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
     <%= f.text_field :name, class: 'form-control', autofocus: true, placeholder:"Nazwa" %>
  </div>
  <div class="field" id="browse">
   <p>
      <strong>Logo:</strong>
      <%= f.file_field :logo %>
   </p>
   </div>
 <div class="sm-offset-0 col-sm-10">
    <%= f.submit "Potwierdź", class: "btn btn-info" %>
  </div>
     <% end %>
  </form>
</div>

app/views/committees/edit.html.erb
<div class="container">  
  <div class="panel-heading"><h2 class="intro-text text-center">Edytuj komitet</h2></div>
    <div class="col-md-offset-1 panel-default">
      <div class="form-horizontal">
      <div>
      <%= render 'form' %>
    </div>
  </div>
</div> 
<div>
  <ul class="pager"> 
    <li><%= link_to 'Powrót', committees_path %></li>
  </ul>
</div>

app/views/committees/index.html.erb
<head>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="table-responsive">
      <div class="panel panel-default">
         <div class="panel-heading">Lista Komitetów Wyborczych</div>
           <table class="table table-bordered table-condensed table-striped">
             <thead>
               <tr>
                <th>Nazwa</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @committees.each do |committee| %>
                <tr>
                 <td><%= committee.name %></td>
                 <td><%= link_to 'Wyświetl', committee %></td>
                 <td><%= link_to 'Edytuj', edit_committee_path(committee) %></td>
                 <td><%= link_to 'Usuń', committee, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
                </tr>
              <% end %>
            </tbody>
         </table>
      </div>
    </div>
  </div>
  <%= link_to 'Dodaj nowy', new_committee_path %>
  </div>

app/views/committees/new.html.erb
<div class="container">
  <div class="content">
  <div class="panel-info"><h3 class="intro-text text-center">Dodaj nowy komitet wyborczy</h3></div>
    <div calss="col-md-offset-6">  
      <%= render 'form' %>
    </div>
   </div>
   <div>
    <ul class="pager">
      <li><%= link_to 'Powrót', committees_path %></li>
    </ul>
   </div>
</div>

app/views/committees/show.html.erb
<div class="container">
    <div class="panel-heading">
      <h2 class="intro-text text-center"><%= @committee.name %></h2>
    </div>
    <div class="intro-text text-center">
      <%= image_tag @committee.logo.url(:medium) %>
    </div>
    <p class="intro-text text-center">   
      <%= link_to 'Edytuj', edit_committee_path(@committee), class: "btn btn-primary" %>
    </p> 
    <div>
    <ul class="pager">
      <li><%= link_to 'Powrót', committees_path %></li>
    </ul>
   </div>
</div>