config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :users
  resources :roles
  resources :committees
  resources :constituencies

  resources :results do

    collection do

       get :sum

    end

  end

   authenticated :user do

    root :to => 'welcome#index_admin', as: :authenticated_root

  end

    root :to => 'welcome#index'   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>System liczenia głosów w wyborach</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<!--header-->

    <div class="page-header">
      <h2>System liczenia głosów </br>
        <small> 
          <% if user_signed_in? %>
            <%= current_user.email %>  
       </small>
      </h2>
      <div class="panel panel-default">
      <div class="col-xs-offset-10">
          <%= link_to "Edytuj profil", edit_user_registration_path, class: "glyphicon-user:before" %> |             
          <%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %>
      </div> 
       <% else %>
         <%= link_to "Zarejestruj", new_user_registration_path %> |  <%= link_to "Zaloguj", new_user_session_path %>
       <% end %>
     </div> 
  </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <% if user_signed_in? %>

<!--navbar-->

    <nav class="navbar navbar-default">
     <div class="container-fluid">
       <div class"navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
           <span class="sr-only"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
       </div>

       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav nav-pills nav-justified">
         <% if user_signed_in? %>
          <% if current_user.admin? %> 
           <li role="presentation" class="active">
             <%= link_to 'Użytkownicy', users_path(@user) %>
           </li>
          <% end %>
         <% end %>
            <li role="presentation" class="active">
             <%= link_to 'Okręgi',  constituencies_path(@constituency) %>
           </li>
             <li role="presentation" class="active">
              <%= link_to 'Komitety', committees_path(@committee) %>
            </li>
             <li role="presentation" class="active">
               <%= link_to 'Wyniki', results_path(@result) %>
             </li>                  
           </ul>
         </div>
        <!--/.navbar-collapse-->
       </div>
       <!--/.container-fluid-->        
     </nav>
    <% end %>
  </div>
  <div class "container">
     <%= yield %>
  </div>
 </body>

<!--footer-->

  <footer class="footer">
      <div class="container">
        <p class="text-muted text-left navabr-fixed-bottom">&copy; 2015 m.koselak EPI UJ</p>
      </div>
  </footer>
</html>   


     